"use client";

import { create } from "zustand";
import { toast } from "sonner";
import type {
  AppNotification,
  ChatMessage,
  CityBriefing,
  EvidenceItem,
  Finding,
  Lang,
  NtfPrefs,
  NotificationKind,
  ProposedAction,
  SasiCase,
  View,
} from "./types";
import {
  CASES,
  DEMO_NOW,
  EVIDENCE,
  FINDINGS,
  INCIDENTS,
  NOTIFICATIONS,
} from "./data";
import { getSessionId } from "./utils";
import {
  clearSnapshotChat,
  offlineSnapshotInfo,
  readSnapshot,
  snapshotBriefing,
  snapshotCase,
  snapshotChat,
  snapshotEvidence,
  snapshotLocation,
  snapshotNotifications,
  type OfflineSnapshotInfo,
  type SnapshotCase,
  type SnapshotMessage,
  type SnapshotNotification,
} from "./offline";

interface SasiState {
  /* ---- navigation (client-side router; the product ships on a single route) ---- */
  view: View;
  param: string | null;
  navigate: (view: View, param?: string) => void;

  /* ---- demo session (drives shell continuity: Services stays in-app) ---- */
  authed: boolean;
  /** display name from the REAL account (null → the neutral "You") */
  accountName: string | null;
  setAccountName: (name: string | null) => void;
  signIn: () => void;
  signOut: () => void;

  /* ---- global command interface ---- */
  commandOpen: boolean;
  setCommandOpen: (open: boolean) => void;

  /* ---- settings deep-link: which section is active (palette/shortcuts write it) ---- */
  settingsSection: string;

  /* ---- notifications (live events on the user's own data only) ---- */
  notifications: AppNotification[];
  markNotificationRead: (id: string) => void;
  markAllNotificationsRead: () => void;
  /** prepend a live notification generated by a real app event (persisted) */
  pushNotification: (
    n: Pick<AppNotification, "kind" | "title" | "body"> &
      Partial<Pick<AppNotification, "id" | "at" | "caseRef">>
  ) => void;
  /** fire after an investigation reaches COMPLETE for a case */
  notifyInvestigationComplete: (caseId: string) => void;

  /* ---- cases (mutable) ---- */
  cases: SasiCase[];
  findings: Record<string, Finding[]>;
  evidence: EvidenceItem[];
  activeCaseId: string | null;
  activeIncidentId: string | null;
  activeService: string | null;

  openCase: (ref: string) => void;
  openIncident: (ref: string) => void;
  openService: (key: string) => void;

  /* ---- persistence ("survive a reload" layer) ---- */
  hydrated: boolean;
  hydrate: () => Promise<void>;
  /** hydrate restored the user's data from the on-device snapshot (network was down) */
  restoredOffline: boolean;
  /** what the on-device IndexedDB snapshot currently holds (Settings → App & offline) */
  deviceSnapshot: OfflineSnapshotInfo | null;
  refreshDeviceSnapshot: () => Promise<void>;

  /* ---- report flow ---- */
  reportDraft: {
    service: string;
    problem: string;
    location: string;
    when: string;
    impact: string;
    evidenceNote: string;
    /** Task 21: device GPS fix + AI/OSM enrichment metadata. When
     *  present, the created case is pinned at the REAL coordinates
     *  instead of the city-level fallback. */
    geo?: {
      lat: number;
      lng: number;
      accuracyM: number | null;
      source: "ai" | "osm" | "coords";
      confidence: string;
      notes: string;
      landmark: string;
      city?: string;
      province?: string;
    } | null;
  } | null;
  setReportDraft: (draft: Partial<NonNullable<SasiState["reportDraft"]>>) => void;
  clearReportDraft: () => void;

  /** create a case from a completed report; returns the new case ref */
  submitReport: () => string;

  /* ---- investigation ---- */
  startInvestigationFor: (caseId: string) => void;
  setCaseAIState: (caseId: string, state: SasiCase["aiState"]) => void;
  addCaseEvent: (caseId: string, event: SasiCase["events"][number]) => void;
  addFinding: (caseId: string, finding: Finding) => void;
  addEvidence: (item: EvidenceItem) => void;
  /** snapshot a case to the server store (best-effort) */
  persistCaseById: (caseId: string) => void;

  /* ---- actions / approval ---- */
  approveAction: (caseId: string) => void;
  rejectAction: (caseId: string) => void;
  setActionState: (caseId: string, state: ProposedAction["state"]) => void;
  setVerification: (
    caseId: string,
    v: SasiCase["verification"]
  ) => void;

  /* ---- saved location / preferences ---- */
  savedLocation: { province: string; city: string; suburb: string };
  setSavedLocation: (loc: Partial<SasiState["savedLocation"]>) => void;

  /* ---- notification preferences (Settings → Notifications, real gating) ---- */
  ntfPrefs: NtfPrefs;
  setNtfPref: (key: keyof NtfPrefs, value: boolean) => void;

  /* ---- interface language (i18n scaffold) ---- */
  lang: Lang;
  setLang: (lang: Lang) => void;

  /* ---- map focus (briefing watchlist → map click-through) ---- */
  /** incident ref (INC-xxxx) the map should highlight, set from the briefing */
  mapFocusRef: string | null;
  focusOnMap: (ref: string) => void;
  clearMapFocus: () => void;

  /* ---- Ask SASI (LLM chat, SSE streaming + persisted) ---- */
  chatMessages: ChatMessage[];
  chatBusy: boolean;
  /** question queued from the palette / other views — consumed by the chat view */
  pendingAsk: string | null;
  setPendingAsk: (q: string | null) => void;
  askSasi: (question: string) => Promise<void>;
  /** stop an in-flight streamed answer — keeps whatever was already received */
  stopSasi: () => void;
  clearChat: () => void;

  /* ---- chat → report loop ---- */
  /** pre-fill the report wizard from an assistant suggestion and open it */
  draftReportFromChat: (messageId: string) => void;

  /* ---- AI City briefing (dashboard digest) ---- */
  briefing: CityBriefing | null;
  briefingBusy: boolean;
  briefingError: string | null;
  /** true when there is no user material to brief from yet — an honest
      empty state (not an error): the briefing is written only from the
      resident's own reports/cases, and none exist so far. */
  briefingEmpty: boolean;
  /** recent briefings, newest first (persisted per session, capped at 8) */
  briefingHistory: CityBriefing[];
  /** the daily city briefing a chat-distilled one displaced (for free restore) */
  cityBriefingBackup: CityBriefing | null;
  /** generate (or regenerate) the daily briefing; caches in sessionStorage */
  generateBriefing: (opts?: { force?: boolean }) => Promise<void>;
  /** restore a briefing cached earlier in this browser session (no network) */
  restoreBriefing: () => void;
  /** distil the current Ask SASI conversation into a briefing (chat → digest reverse link) */
  briefingFromChat: () => Promise<void>;
  /** swap a chat-distilled card back to the daily city briefing it replaced */
  restoreCityBriefing: () => Promise<void>;
}

let caseCounter = 1;
let eventCounter = 1;

/** keep ref generation ahead of any case restored from the persisted store */
function bumpCaseCounterFrom(c: SasiCase) {
  const refNum = Number(/^CASE-(\d{6})$/.exec(c.ref)?.[1] ?? 0);
  const idNum = Number(/^case-new-(\d+)$/.exec(c.id)?.[1] ?? 0);
  const max = Math.max(refNum, idNum);
  if (Number.isFinite(max) && max >= caseCounter) caseCounter = max + 1;
}

/* ---------- persistence helpers (fire-and-forget; the demo never blocks on storage) ---------- */

async function persistCase(c: SasiCase) {
  /* mirror into the on-device snapshot first — an offline reload must
     still show this case even if the server POST below never lands */
  void snapshotCase(c as unknown as SnapshotCase);
  try {
    await fetch("/api/sasi/state", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ type: "case", sessionId: getSessionId(), case: c }),
    });
  } catch {
    /* offline / demo — the in-memory case (and snapshot) still work */
  }
}

async function persistBriefing(b: CityBriefing) {
  void snapshotBriefing(b);
  try {
    await fetch("/api/sasi/state", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ type: "briefing", sessionId: getSessionId(), briefing: b }),
    });
  } catch {
    /* offline / demo — the session cache + device snapshot cover this visit */
  }
}

async function persistNotification(n: AppNotification) {
  try {
    await fetch("/api/sasi/state", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ type: "notification", sessionId: getSessionId(), notification: n }),
    });
  } catch {
    /* offline / demo — the in-memory notification still works */
  }
}

function persistNotificationRead(opts: { notificationId?: string; all?: boolean }) {
  void fetch("/api/sasi/state", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ type: "notification-read", sessionId: getSessionId(), ...opts }),
  }).catch(() => undefined);
}

/** mirror the current in-memory notification list into the on-device snapshot */
function mirrorNotifications(list: AppNotification[]) {
  void snapshotNotifications(list as unknown as SnapshotNotification[]);
}

/** mirror the finished half of the chat into the on-device snapshot */
function mirrorChat(list: ChatMessage[]) {
  const done: SnapshotMessage[] = list
    .filter((m) => m.state === "done" && m.content.trim())
    .map((m) => ({ id: m.id, role: m.role, content: m.content, at: m.at, refs: m.refs }));
  void snapshotChat(done);
}

/** abort handle for the in-flight Ask SASI stream (stop-generation) */
let chatAbort: AbortController | null = null;

/** newest first, capped — shared by push and hydrate merges */
function mergeNotifications(current: AppNotification[], incoming: AppNotification[]): AppNotification[] {
  const byId = new globalThis.Map<string, AppNotification>();
  for (const n of current) byId.set(n.id, n);
  for (const n of incoming) {
    const existing = byId.get(n.id);
    /* read-state OR-ed so a read stays read across rehydrates */
    byId.set(n.id, existing ? { ...n, read: existing.read || n.read } : n);
  }
  return Array.from(byId.values())
    .sort((a, b) => b.at.localeCompare(a.at))
    .slice(0, 30);
}

/** merge a briefing into the history (newest first, deduped, capped) */
function pushBriefingHistory(history: CityBriefing[], b: CityBriefing): CityBriefing[] {
  const next = [b, ...history.filter((h) => h.generatedAt !== b.generatedAt)];
  return next
    .slice(0, 8)
    .sort((x, y) => y.generatedAt.localeCompare(x.generatedAt));
}

/** briefings older than this are considered stale and quietly refreshed */
const BRIEFING_TTL_MS = 6 * 60 * 60 * 1000;

/* ------------------------------------------------------------------
   Shared merge for user data arriving from EITHER source — the
   on-device IndexedDB snapshot (offline) or /api/sasi/state (the
   server copy, which takes precedence when reachable). Both use
   the same dedupe + prepend rules, so hydrate stays honest:
   server rows win only by merging after the snapshot.
   ------------------------------------------------------------------ */
interface RemotePayload {
  cases?: SasiCase[];
  chat?: { id: string; role: "user" | "assistant"; content: string; at: string; refs?: string[] }[];
  evidence?: EvidenceItem[];
  location?: { province: string; city: string; suburb: string };
  briefings?: CityBriefing[];
  briefing?: CityBriefing | null;
  notifications?: AppNotification[];
}

function mergeRemote(
  s: SasiState,
  remote: RemotePayload
): Partial<SasiState> {
  const userCases = (remote.cases ?? []).filter(
    (c) => !s.cases.some((existing) => existing.ref === c.ref)
  );
  for (const c of remote.cases ?? []) bumpCaseCounterFrom(c);
  const userEvidence = (remote.evidence ?? []).filter(
    (ev) => !s.evidence.some((existing) => existing.id === ev.id)
  );
  const chat =
    s.chatMessages.length === 0 && (remote.chat?.length ?? 0) > 0
      ? (remote.chat ?? []).map<ChatMessage>((m) => ({
          id: m.id,
          role: m.role,
          content: m.content,
          at: m.at,
          state: "done",
          refs: m.refs,
        }))
      : s.chatMessages;
  let history = s.briefingHistory;
  for (const b of remote.briefings ?? []) history = pushBriefingHistory(history, b);
  /* a single cached briefing (device snapshot) fills the card + history */
  let liveBriefing = s.briefing;
  if (!liveBriefing && remote.briefing) {
    liveBriefing = remote.briefing;
    history = pushBriefingHistory(history, remote.briefing);
  }
  return {
    cases: userCases.length ? [...userCases, ...s.cases] : s.cases,
    evidence: userEvidence.length ? [...userEvidence, ...s.evidence] : s.evidence,
    chatMessages: chat,
    savedLocation: remote.location ?? s.savedLocation,
    briefingHistory: history,
    ...(liveBriefing && !s.briefing ? { briefing: liveBriefing } : {}),
    notifications: mergeNotifications(s.notifications, remote.notifications ?? []),
  };
}

/* ------------------------------------------------------------------
   Notification preferences — persisted per browser so the user's
   quiet/calm configuration survives reloads. The briefing (UPDATE)
   digest is gated too: it is the heartbeat, but the user can quiet it
   (the Settings note explains what they might miss).
   ------------------------------------------------------------------ */
const DEFAULT_NTF_PREFS: NtfPrefs = {
  case: true,
  investigation: true,
  action: true,
  service: false,
  digest: true,
};

function loadNtfPrefs(): NtfPrefs {
  if (typeof window === "undefined") return DEFAULT_NTF_PREFS;
  try {
    const raw = window.localStorage.getItem("sasi.ntfPrefs");
    if (!raw) return DEFAULT_NTF_PREFS;
    const parsed = JSON.parse(raw) as Partial<NtfPrefs>;
    return { ...DEFAULT_NTF_PREFS, ...parsed };
  } catch {
    return DEFAULT_NTF_PREFS;
  }
}

function persistNtfPrefs(prefs: NtfPrefs) {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem("sasi.ntfPrefs", JSON.stringify(prefs));
  } catch {
    /* storage blocked — prefs stay session-only */
  }
}

/** which Settings toggle gates a live notification kind (all five are user-controlled) */
function prefGatesKind(prefs: NtfPrefs, kind: NotificationKind): boolean {
  switch (kind) {
    case "CASE":
      return prefs.case;
    case "INVESTIGATION":
      return prefs.investigation;
    case "ACTION":
      return prefs.action;
    case "SYSTEM":
      return prefs.service;
    case "UPDATE":
      return prefs.digest; // briefing heartbeat — quietable via Settings
  }
}

/** every view the SPA knows — used to validate /?view= deep links (PWA shortcuts) */
const ALL_VIEWS: readonly View[] = [
  "landing",
  "about",
  "how-it-works",
  "services",
  "service-detail",
  "security",
  "privacy",
  "terms",
  "gov",
  "login",
  "signup",
  "dashboard",
  "ask-sasi",
  "investigate",
  "start-investigation",
  "report",
  "cases",
  "case-detail",
  "incidents",
  "incident-detail",
  "map",
  "evidence",
  "activity",
  "notifications",
  "settings",
  "profile",
  "admin",
];

let locationSaveTimer: ReturnType<typeof setTimeout> | null = null;
function persistLocation(loc: SasiState["savedLocation"]) {
  void snapshotLocation(loc);
  if (locationSaveTimer) clearTimeout(locationSaveTimer);
  locationSaveTimer = setTimeout(() => {
    void fetch("/api/sasi/state", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ type: "location", sessionId: getSessionId(), location: loc }),
    }).catch(() => undefined);
  }, 600);
}

/* ==================================================================
   BROWSER HISTORY BRIDGE (Task 23) — the state router becomes a real
   router: every view change pushes /?view=x(&p=y) so the browser Back
   button, the Android back gesture and the PWA back control all work;
   popstate parses the URL back into the store (auth-gated, honest
   fallbacks for stale/unknown detail params).
   ================================================================== */

/** views reachable without a session (mirrors the old PUBLIC_VIEW_SET) */
const PUBLIC_VIEWS: ReadonlySet<string> = new Set<View>([
  "landing",
  "about",
  "how-it-works",
  "services",
  "service-detail",
  "security",
  "privacy",
  "terms",
  "login",
  "signup",
]);

let applyingPop = false; /* suppresses the push subscriber during URL→store sync */

function sasiUrlFor(view: View, param: string | null): string {
  if (typeof window === "undefined") return "/";
  if (view === "landing") return window.location.pathname;
  const q = new URLSearchParams();
  q.set("view", view);
  if (param) q.set("p", param);
  return `${window.location.pathname}?${q.toString()}`;
}

/** URL → store (no push). Stale/unknown detail params fall back to the
    honest list view instead of a broken detail screen. */
function applySasiUrl(): void {
  if (typeof window === "undefined") return;
  try {
    const url = new URL(window.location.href);
    const rawView = url.searchParams.get("view");
    const rawParam = url.searchParams.get("p");
    const view: View =
      rawView && (ALL_VIEWS as readonly string[]).includes(rawView)
        ? (rawView as View)
        : "landing";
    const s = useSasiStore.getState();
    let target = view;
    let targetParam = rawParam;
    if (!PUBLIC_VIEWS.has(view)) {
      /* app views need a session — signed-out back-navigation lands on login */
      if (!s.authed) {
        target = "login";
        targetParam = null;
      }
    } else if (s.authed && (view === "login" || view === "signup")) {
      /* already signed in — no reason to deep-link into the auth forms */
      target = "dashboard";
      targetParam = null;
    }
    if (targetParam !== null) targetParam = targetParam.trim() || null;
    applyingPop = true;
    useSasiStore.setState({
      view: target,
      param: targetParam,
      commandOpen: false,
    });
    applyingPop = false;
    window.scrollTo(0, 0);
  } catch {
    /* history API blocked — the app keeps its current view */
  }
}

export const useSasiStore = create<SasiState>((set, get) => ({
  view: "landing",
  param: null,
  navigate: (view, param) => {
    set({
      view,
      param: param ?? null,
      commandOpen: false,
    });
    /* smoother navigation: every view change starts at the top of the page —
       no half-scrolled surprises, no lost users (Task 16) */
    if (typeof window !== "undefined") window.scrollTo(0, 0);
  },

  /* ---------- demo session ---------- */
  authed: false,
  accountName: null,
  setAccountName: (name) => {
    set({ accountName: name && name.trim() ? name.trim() : null });
    try {
      if (name && name.trim()) window.localStorage.setItem("sasi.accountName", name.trim());
      else window.localStorage.removeItem("sasi.accountName");
    } catch {
      /* storage blocked — session-only name */
    }
  },
  signIn: () => {
    set({ authed: true });
    try {
      window.localStorage.setItem("sasi.authed", "1");
    } catch {
      /* storage blocked — session-only sign-in */
    }
  },
  signOut: () => {
    set({ authed: false });
    try {
      window.localStorage.removeItem("sasi.authed");
    } catch {
      /* ignore */
    }
    toast("Signed out", {
      description: "Your saved cases stay on this browser for next time.",
    });
  },

  /* ---------- AI City briefing ---------- */
  briefing: null,
  briefingBusy: false,
  briefingError: null,
  briefingEmpty: false,
  briefingHistory: [],
  restoreBriefing: () => {
    if (typeof window === "undefined") return;
    try {
      const raw = window.sessionStorage.getItem("sasi.briefing");
      if (!raw) return;
      const cached = JSON.parse(raw) as CityBriefing;
      /* only restore if it matches the current location (cheap sanity check) */
      if (cached?.headline && cached?.sections?.length) {
        set({
          briefing: cached,
          briefingHistory: pushBriefingHistory(get().briefingHistory, cached),
        });
      }
    } catch {
      /* corrupt cache — ignore, user can regenerate */
    }
  },
  generateBriefing: async (opts) => {
    if (get().briefingBusy) return;
    if (!opts?.force) {
      if (!get().briefing) get().restoreBriefing();
      const cached = get().briefing;
      if (cached) {
        const age = Date.now() - new Date(cached.generatedAt).getTime();
        if (age < BRIEFING_TTL_MS) return; // fresh enough — no LLM call
      }
      /* stale (older than 6h) or missing → fall through and rewrite quietly */
    }
    /* The daily briefing is grounded ONLY in the resident's own material
       (their reports/cases). With none yet there is nothing to brief —
       show the honest empty state instead of asking the AI to invent one. */
    if (get().cases.length === 0) {
      set({ briefingBusy: false, briefingError: null, briefingEmpty: true });
      return;
    }
    set({ briefingBusy: true, briefingError: null, briefingEmpty: false });
    try {
      const res = await fetch("/api/sasi/briefing", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          location: get().savedLocation,
          /* the user's live cases ground the briefing (and its refs) */
          extraCases: get()
            .cases.slice(0, 8)
            .map((c) => ({
              ref: c.ref,
              title: c.title,
              status: c.status,
              service: c.service,
              city: c.location.city,
              actionState: c.proposedAction?.state,
            })),
        }),
      });
      const data = (await res.json()) as {
        briefing?: CityBriefing | null;
        error?: string;
        empty?: boolean;
      };
      /* honest no-material response from the route (contract-stable) */
      if (data.empty) {
        set({ briefingBusy: false, briefingError: null, briefingEmpty: true });
        return;
      }
      if (!res.ok || !data.briefing) {
        throw new Error(data.error ?? "SASI could not write the briefing right now.");
      }
      const b = data.briefing;
      set((s) => ({
        briefing: b,
        briefingBusy: false,
        briefingEmpty: false,
        briefingHistory: pushBriefingHistory(s.briefingHistory, b),
      }));
      try {
        window.sessionStorage.setItem("sasi.briefing", JSON.stringify(b));
      } catch {
        /* storage full/blocked — briefing stays in memory */
      }
      void persistBriefing(b);
      /* a fresh briefing is a real signal — feed the live digest */
      const riskLabel =
        b.risk === "CALM"
          ? "Calm"
          : b.risk === "STRAINED"
            ? "Strained"
            : b.risk === "CRITICAL"
              ? "Critical"
              : "Elevated";
      get().pushNotification({
        id: `ntf-live-briefing-${b.generatedAt}`,
        kind: "UPDATE",
        title: `City briefing ready · ${riskLabel}`,
        body: b.headline,
      });
    } catch (err) {
      /* a stale cached briefing is still better than an error panel — keep it visible */
      set({
        briefingBusy: false,
        briefingError:
          err instanceof Error && err.message
            ? err.message
            : "SASI could not write the briefing right now.",
      });
    }
  },

  /* ---- chat → briefing reverse link: distil this conversation ----
     Replaces today's card, but the city briefing it displaces is kept
     in cityBriefingBackup so "City mode" can restore it for free. */
  briefingFromChat: async () => {
    const previous = get().briefing;
    if (previous && previous.origin !== "chat") {
      set({ cityBriefingBackup: previous });
    }
    if (get().briefingBusy) return;
    const transcript = get()
      .chatMessages.filter((m) => m.state === "done" && m.content.trim())
      .slice(-12)
      .map((m) => ({ role: m.role, content: m.content }));
    if (transcript.length < 2) {
      toast("Nothing to summarise yet", {
        description: "Ask SASI something first — then distil the answer into a briefing.",
      });
      return;
    }
    set({ briefingBusy: true, briefingError: null });
    try {
      const res = await fetch("/api/sasi/briefing", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          location: get().savedLocation,
          origin: "chat",
          transcript,
        }),
      });
      const data = (await res.json()) as { briefing?: CityBriefing; error?: string };
      if (!res.ok || !data.briefing) {
        throw new Error(data.error ?? "SASI could not distil this conversation right now.");
      }
      const b = data.briefing;
      set((s) => ({
        briefing: b,
        briefingBusy: false,
        briefingEmpty: false,
        briefingHistory: pushBriefingHistory(s.briefingHistory, b),
      }));
      try {
        window.sessionStorage.setItem("sasi.briefing", JSON.stringify(b));
      } catch {
        /* storage full/blocked — briefing stays in memory */
      }
      void persistBriefing(b);
      get().pushNotification({
        id: `ntf-live-briefing-chat-${b.generatedAt}`,
        kind: "UPDATE",
        title: "Briefing written from your conversation",
        body: b.headline,
      });
      set({ view: "dashboard", param: null, commandOpen: false });
      toast("Briefing distilled from your chat", {
        description: "It replaces today's card — City mode on the card restores the daily digest.",
      });
    } catch (err) {
      set({
        briefingBusy: false,
        briefingError:
          err instanceof Error && err.message
            ? err.message
            : "SASI could not distil this conversation right now.",
      });
      toast.error("Could not write the briefing", {
        description: "Your conversation is untouched — try again in a moment.",
      });
    }
  },

  commandOpen: false,
  setCommandOpen: (open) => set({ commandOpen: open }),

  settingsSection: "account",

  cityBriefingBackup: null,
  restoreCityBriefing: async () => {
    const backup = get().cityBriefingBackup;
    if (backup) {
      set({ briefing: backup, cityBriefingBackup: null });
      try {
        window.sessionStorage.setItem("sasi.briefing", JSON.stringify(backup));
      } catch {
        /* storage full/blocked — briefing stays in memory */
      }
      toast("City briefing restored", {
        description: "You're back on the daily digest for your area.",
      });
      return;
    }
    /* no backup (e.g. reload after distilling) — honest fallback: rewrite */
    toast("Rewriting your city briefing…", {
      description: "The daily digest isn't cached on this browser, so SASI is writing a fresh one.",
    });
    await get().generateBriefing({ force: true });
  },

  notifications: NOTIFICATIONS,
  markNotificationRead: (id) => {
    set((s) => ({
      notifications: s.notifications.map((n) =>
        n.id === id ? { ...n, read: true } : n
      ),
    }));
    const n = get().notifications.find((x) => x.id === id);
    if (n?.live) persistNotificationRead({ notificationId: id });
    mirrorNotifications(get().notifications);
  },
  markAllNotificationsRead: () => {
    set((s) => ({
      notifications: s.notifications.map((n) => ({ ...n, read: true })),
    }));
    persistNotificationRead({ all: true });
    mirrorNotifications(get().notifications);
  },
  /* ---------- notification preferences ---------- */
  ntfPrefs: DEFAULT_NTF_PREFS,
  setNtfPref: (key, value) => {
    const prefs = { ...get().ntfPrefs, [key]: value };
    set({ ntfPrefs: prefs });
    persistNtfPrefs(prefs);
    const label =
      key === "case"
        ? "Case updates"
        : key === "investigation"
          ? "Investigation findings"
          : key === "action"
            ? "Action approvals"
            : key === "digest"
              ? "Briefing digest"
              : "Service alerts";
    toast(`Notification preference saved`, {
      description: `${label} ${value ? "on" : "off"} — SASI stops or resumes those alerts right away.`,
    });

    /* No demo service alerts: notifications are raised only by real
       events on the resident's own data (reports, investigations,
       approvals, briefings). Nothing is generated from a dataset. */
  },

  pushNotification: (partial) => {
    /* Settings → Notifications gate: the toggle decides whether this
       event family may raise an alert at all. UPDATE (briefing) passes. */
    if (!prefGatesKind(get().ntfPrefs, partial.kind)) return;
    const n: AppNotification = {
      id: partial.id ?? `ntf-live-${Date.now()}-${Math.floor(Math.random() * 1e4)}`,
      kind: partial.kind,
      title: partial.title,
      body: partial.body,
      at: partial.at ?? new Date().toISOString(),
      read: false,
      caseRef: partial.caseRef,
      live: true,
    };
    set((s) => ({ notifications: mergeNotifications([n], s.notifications) }));
    void persistNotification(n);
    /* keep the on-device snapshot in sync (offline reloads show this) */
    mirrorNotifications(get().notifications);
  },
  notifyInvestigationComplete: (caseId) => {
    const c = get().cases.find((x) => x.id === caseId);
    if (!c) return;
    get().pushNotification({
      id: `ntf-live-inv-${c.ref}-${Date.now()}`,
      kind: "INVESTIGATION",
      title: `Investigation complete · ${c.ref}`,
      body: "Findings and a proposed action are ready for your review. Nothing was sent without you.",
      caseRef: c.ref,
    });
  },

  /* the user's data — starts EMPTY; hydrate merges only what the
     resident actually created (server copy + on-device snapshot) */
  cases: CASES,
  findings: FINDINGS,
  evidence: EVIDENCE,
  activeCaseId: null,
  activeIncidentId: null,
  activeService: "water",

  openCase: (ref) => {
    const c = get().cases.find((x) => x.ref === ref || x.id === ref);
    set({ activeCaseId: c?.id ?? null, view: "case-detail", param: ref, commandOpen: false });
  },
  openIncident: (ref) => {
    /* fail SOFT: incidents are user-generated now, so an unknown or
       absent ref (e.g. a stale INC-… citation) lands on the honest
       incidents list instead of a broken detail view */
    const known = INCIDENTS.some(
      (i) => i.id === ref || i.ref.toLowerCase() === ref.toLowerCase()
    );
    if (!known) {
      set({ activeIncidentId: null, view: "incidents", param: null, commandOpen: false });
      return;
    }
    set({ activeIncidentId: ref, view: "incident-detail", param: ref, commandOpen: false });
  },
  openService: (key) => {
    set({ activeService: key, view: "service-detail", param: key, commandOpen: false });
  },

  /* ------------------------------------------------------------------
     Hydrate — load the user's cases, chat history and saved location
     from the on-device IndexedDB snapshot FIRST (so an offline reload
     still shows the user's work), then from /api/sasi/state (keyed by
     an anonymous browser session id; the server copy merges over the
     snapshot and wins where they differ). Runs once while the splash
     screen is up; failures are silent and the demo falls back to its
     in-memory dataset.
     ------------------------------------------------------------------ */
  hydrated: false,
  restoredOffline: false,
  deviceSnapshot: null,
  refreshDeviceSnapshot: async () => {
    set({ deviceSnapshot: await offlineSnapshotInfo() });
  },
  hydrate: async () => {
    if (get().hydrated || typeof window === "undefined") return;
    set({ hydrated: true }); // guard against double-invoke before the fetch resolves
    /* restore the demo session flag so Services stays in the app shell across reloads */
    try {
      if (window.localStorage.getItem("sasi.authed") === "1") set({ authed: true });
      try {
        const savedName = window.localStorage.getItem("sasi.accountName");
        if (savedName) set({ accountName: savedName });
      } catch {
        /* ignore */
      }
      const savedLang = window.localStorage.getItem("sasi.lang");
      if (savedLang === "en" || savedLang === "zu" || savedLang === "af") {
        set({ lang: savedLang });
        document.documentElement.lang = savedLang;
      }
      /* restore the user's notification preferences (Settings → Notifications) */
      set({ ntfPrefs: loadNtfPrefs() });
    } catch {
      /* storage blocked — session-only */
    }

    /* ---------- 1. on-device snapshot (IndexedDB) — works with no network ---------- */
    let haveSnapshot = false;
    try {
      const snap = await readSnapshot();
      if (
        (snap.cases?.length ?? 0) > 0 ||
        (snap.chat?.length ?? 0) > 0 ||
        (snap.notifications?.length ?? 0) > 0 ||
        (snap.evidence?.length ?? 0) > 0 ||
        snap.location ||
        snap.briefing
      ) {
        haveSnapshot = true;
        set((s) =>
          mergeRemote(s, {
            cases: snap.cases as unknown as SasiCase[] | undefined,
            chat: snap.chat ?? undefined,
            evidence: snap.evidence as unknown as EvidenceItem[] | undefined,
            location: snap.location ?? undefined,
            briefing: (snap.briefing as CityBriefing | null) ?? undefined,
            notifications: snap.notifications as AppNotification[] | undefined,
          })
        );
        /* the snapshot briefing also seeds the session cache so
           restoreBriefing / City mode keep working offline */
        const b = get().briefing;
        if (b) {
          try {
            window.sessionStorage.setItem("sasi.briefing", JSON.stringify(b));
          } catch {
            /* storage full/blocked — briefing stays in memory */
          }
        }
      }
    } catch {
      /* snapshot unavailable — demo continues from memory */
    }
    void get().refreshDeviceSnapshot();

    const offline = typeof navigator !== "undefined" && !navigator.onLine;
    if (haveSnapshot && offline) set({ restoredOffline: true });

    /* ---------- 2. server copy (source of truth when reachable) ---------- */
    if (!offline) {
      try {
        const res = await fetch(`/api/sasi/state?sessionId=${encodeURIComponent(getSessionId())}`);
        if (res.ok) {
          const data = (await res.json()) as RemotePayload;
          set((s) => mergeRemote(s, data));
          /* warm the city briefing so the notifications digest (and any view
             that cites it) has data — TTL/session-cache guarded, so this is
             free when the cache is fresh. SKIPPED while offline: the LLM
             call would fail; the snapshot briefing covers the card. */
          void get().generateBriefing();
        } else if (haveSnapshot) {
          set({ restoredOffline: true });
        }
      } catch {
        if (haveSnapshot) set({ restoredOffline: true });
      }
    }

    /* No demo service alerts on hydrate: notifications exist only for
       real events on the resident's own data. Incidents are no longer
       simulated, so there is nothing to digest at startup. */

    /* an offline restore is worth one honest, quiet announcement */
    if (get().restoredOffline) {
      toast("Restored from this device", {
        description: "You're offline — SASI is showing your saved cases, chat and alerts from the on-device copy.",
      });
    }

    /* ---------- deep link: /?view=report (PWA manifest shortcuts) ----------
       Runs once at hydrate; only honoured for known views, and only when
       the target is reachable in the current auth state (a shortcut to an
       app view while signed out lands on the login view instead — honest). */
    try {
      const wanted = new URLSearchParams(window.location.search).get("view");
      if (wanted) {
        const known = (ALL_VIEWS as readonly string[]).includes(wanted);
        if (known) {
          const authed = get().authed;
          const isPublic = PUBLIC_VIEWS.has(wanted);
          if (!authed && !isPublic) {
            /* an app shortcut while signed out lands on login — honest */
            applyingPop = true;
            get().navigate("login");
            applyingPop = false;
          } else {
            /* full URL sync handles ?p= for detail views; the push
               subscriber stays suppressed so boot doesn't double-stack
               history entries */
            applySasiUrl();
          }
        }
        /* the boot entry BECOMES the app URL: one Back step leaves the
           app instead of replaying the deep link */
        window.history.replaceState(
          { sasi: true },
          "",
          sasiUrlFor(get().view, get().param)
        );
      }
    } catch {
      /* history API blocked — the deep link simply keeps its query */
    }
  },

  reportDraft: null,
  setReportDraft: (draft) =>
    set((s) => ({
      reportDraft: { ...(s.reportDraft ?? { service: "water", problem: "", location: "", when: "today", impact: "", evidenceNote: "" }), ...draft },
    })),
  clearReportDraft: () => set({ reportDraft: null }),

  submitReport: () => {
    const draft = get().reportDraft ?? {
      service: "water",
      problem: "Issue reported via SASI",
      location: "",
      when: "today",
      impact: "",
      evidenceNote: "",
    };
    const nowIso = new Date().toISOString();
    const id = `case-new-${caseCounter}`;
    const finalRef = `CASE-${String(caseCounter).padStart(6, "0")}`;
    caseCounter += 1;
    /* Task 21: a GPS-backed draft pins the case at the REAL device
       coordinates (projected into the stylised map space too), so
       map markers land exactly where the reporter stood instead of
       the city-centre fallback. */
    const geo = draft.geo ?? null;
    const geoX =
      geo && Number.isFinite(geo.lng)
        ? Math.min(100, Math.max(0, (geo.lng - 27.51385) / 0.010135))
        : undefined;
    const geoY =
      geo && Number.isFinite(geo.lat)
        ? Math.min(100, Math.max(0, (geo.lat - -25.58251) / -0.0109497))
        : undefined;
    const newCase: SasiCase = {
      id,
      ref: finalRef,
      title: draft.problem || "New report",
      description: draft.impact || draft.problem,
      service: (draft.service as SasiCase["service"]) || "water",
      location: {
        province: geo?.province || get().savedLocation.province,
        municipality: "",
        city: geo?.city || draft.location.split(",")[0]?.trim() || get().savedLocation.city,
        suburb: draft.location,
        ...(geo
          ? {
              lat: geo.lat,
              lng: geo.lng,
              mapX: geoX,
              mapY: geoY,
            }
          : {}),
      },
      status: "OPEN",
      priority: "MEDIUM",
      createdAt: nowIso,
      updatedAt: nowIso,
      aiState: "IDLE",
      impact: draft.impact,
      events: [
        {
          id: `ev-${eventCounter++}`,
          at: nowIso,
          label: "Report received",
          detail: "You reported this to SASI. This is not yet a government submission.",
          kind: "user",
        },
      ],
    };
    set((s) => ({
      cases: [newCase, ...s.cases],
      activeCaseId: id,
      findings: { ...s.findings, [id]: [] },
      reportDraft: null,
    }));
    void persistCase(newCase);
    get().pushNotification({
      id: `ntf-live-case-${finalRef}`,
      kind: "CASE",
      title: `Report ${finalRef} received`,
      body: "Your report is on this browser only. SASI has not contacted any authority.",
      caseRef: finalRef,
    });
    toast.success(`Report ${finalRef} created`, {
      description: "Saved to this browser — it will still be here when you come back.",
    });
    return finalRef;
  },

  startInvestigationFor: (caseId) => {
    set((s) => ({
      activeCaseId: caseId,
      view: "investigate",
      param: caseId,
      cases: s.cases.map((c) =>
        c.id === caseId
          ? {
              ...c,
              status: c.status === "OPEN" ? "INVESTIGATING" : c.status,
              aiState: "UNDERSTANDING",
              updatedAt: new Date().toISOString(),
            }
          : c
      ),
    }));
    const c = get().cases.find((x) => x.id === caseId);
    if (c) void persistCase(c);
  },
  setCaseAIState: (caseId, state) =>
    set((s) => ({
      cases: s.cases.map((c) =>
        c.id === caseId ? { ...c, aiState: state, updatedAt: new Date().toISOString() } : c
      ),
    })),
  addCaseEvent: (caseId, event) =>
    set((s) => ({
      cases: s.cases.map((c) =>
        c.id === caseId ? { ...c, events: [...c.events, event] } : c
      ),
    })),
  addFinding: (caseId, finding) =>
    set((s) => ({
      findings: { ...s.findings, [caseId]: [...(s.findings[caseId] ?? []), finding] },
    })),
  addEvidence: (item) => {
    set((s) => ({ evidence: [item, ...s.evidence] }));
    void snapshotEvidence(item);
    void fetch("/api/sasi/state", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ type: "evidence", sessionId: getSessionId(), evidence: item }),
    }).catch(() => undefined);
  },
  persistCaseById: (caseId) => {
    const c = get().cases.find((x) => x.id === caseId);
    if (c) void persistCase(c);
  },

  approveAction: (caseId) => {
    const c = get().cases.find((x) => x.id === caseId);
    if (!c?.proposedAction) return;
    get().setActionState(caseId, "APPROVED");
    get().addCaseEvent(caseId, {
      id: `ev-${eventCounter++}`,
      at: new Date().toISOString(),
      label: "You approved the action",
      detail: c.proposedAction.title,
      kind: "action",
    });
    get().pushNotification({
      id: `ntf-live-approved-${c.ref}-${Date.now()}`,
      kind: "ACTION",
      title: "Action approved",
      body: `You approved: ${c.proposedAction?.title}. SASI is executing.`,
      caseRef: c.ref,
    });
    void persistCase(get().cases.find((x) => x.id === caseId) ?? c);
    toast.success("Action approved — SASI is executing", {
      description: `${c.ref} · ${c.proposedAction?.title ?? ""}`.trim(),
    });
  },
  rejectAction: (caseId) => {
    const c = get().cases.find((x) => x.id === caseId);
    if (!c?.proposedAction) return;
    get().setActionState(caseId, "REJECTED");
    get().setCaseAIState(caseId, "PAUSED");
    get().addCaseEvent(caseId, {
      id: `ev-${eventCounter++}`,
      at: new Date().toISOString(),
      label: "You rejected the action",
      detail: "SASI will not proceed. You can revisit this later.",
      kind: "action",
    });
    void persistCase(get().cases.find((x) => x.id === caseId) ?? c);
    toast("Action rejected — SASI paused", {
      description: `${c.ref} · nothing was sent. You can revisit this later.`,
    });
  },
  setActionState: (caseId, state) =>
    set((s) => ({
      cases: s.cases.map((c) =>
        c.id === caseId && c.proposedAction
          ? { ...c, proposedAction: { ...c.proposedAction, state } }
          : c
      ),
    })),
  setVerification: (caseId, v) =>
    set((s) => ({
      cases: s.cases.map((c) => (c.id === caseId ? { ...c, verification: v } : c)),
    })),

  savedLocation: { province: "Gauteng", city: "Johannesburg", suburb: "Melrose" },
  setSavedLocation: (loc) => {
    set((s) => ({ savedLocation: { ...s.savedLocation, ...loc } }));
    persistLocation(get().savedLocation);
  },

  /* ---------- interface language ---------- */
  lang: "en",
  setLang: (lang) => {
    set({ lang });
    try {
      window.localStorage.setItem("sasi.lang", lang);
    } catch {
      /* storage blocked — session-only language */
    }
    if (typeof document !== "undefined") {
      document.documentElement.lang = lang;
    }
  },

  /* ---------- map focus ---------- */
  mapFocusRef: null,
  focusOnMap: (ref) => {
    /* CASE refs resolve against the user's own cases (placed at their saved
       location); everything else must be a demo incident. */
    const known =
      (ref.toUpperCase().startsWith("CASE-") &&
        get().cases.some((c) => c.ref.toUpperCase() === ref.toUpperCase())) ||
      INCIDENTS.some(
        (i) => i.ref.toLowerCase() === ref.toLowerCase() || i.id === ref.toLowerCase()
      );
    if (!known) {
      toast("Nothing to show on the map", {
        description: `${ref} isn't one of your mappable reports, so SASI cannot focus it.`,
      });
      return;
    }
    set({ mapFocusRef: ref.toUpperCase(), view: "map", param: null, commandOpen: false });
  },
  clearMapFocus: () => set({ mapFocusRef: null }),

  /* ------------------------------------------------------------------
     Ask SASI — free-text civic assistant backed by /api/sasi/ask.
     The reply arrives as Server-Sent Events: deltas append to the
     assistant bubble in real time, the done event carries refs and
     suggested follow-up actions. The server persists both sides of
     the conversation per browser session. On failure the user gets
     an honest error bubble instead of a fabricated answer.
     ------------------------------------------------------------------ */
  chatMessages: [],
  chatBusy: false,
  pendingAsk: null,
  setPendingAsk: (q) => set({ pendingAsk: q }),
  stopSasi: () => {
    chatAbort?.abort();
  },
  clearChat: () => {
    set({ chatMessages: [], pendingAsk: null });
    void clearSnapshotChat();
    void fetch(
      `/api/sasi/state?sessionId=${encodeURIComponent(getSessionId())}&scope=chat`,
      { method: "DELETE" }
    ).catch(() => undefined);
    toast("Conversation cleared", {
      description: "Chat history was removed from this browser and from SASI's memory.",
    });
  },
  askSasi: async (question) => {
    const trimmed = question.trim();
    if (!trimmed || get().chatBusy) return;

    const userMsg: ChatMessage = {
      id: `chat-u-${Date.now()}`,
      role: "user",
      content: trimmed,
      at: new Date().toISOString(),
      state: "done",
    };
    const history = [...get().chatMessages, userMsg];
    const replyId = `chat-a-${Date.now()}`;
    set({
      chatMessages: [
        ...history,
        { id: replyId, role: "assistant", content: "", at: new Date().toISOString(), state: "sending" },
      ],
      chatBusy: true,
    });

    const patchReply = (patch: Partial<ChatMessage>) =>
      set((s) => ({
        chatMessages: s.chatMessages.map((m) =>
          m.id === replyId ? { ...m, ...patch } : m
        ),
      }));

    chatAbort = new AbortController();
    const { signal } = chatAbort;

    try {
      const res = await fetch("/api/sasi/ask", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        signal,
        body: JSON.stringify({
          messages: history
            .filter((m) => m.state === "done")
            .slice(-10)
            .map((m) => ({ role: m.role, content: m.content })),
          location: get().savedLocation,
          /* the resident's LIVE cases — Ask SASI grounds its answers in
             real data only (no demo dataset exists anywhere) */
          cases: get()
            .cases
            .slice(0, 12)
            .map((c) => ({
              ref: c.ref,
              title: c.title,
              status: c.status,
              service: c.service,
              city: c.location?.city,
              aiState: c.aiState,
            })),
          sessionId: getSessionId(),
          stream: true,
        }),
      });

      const contentType = res.headers.get("content-type") ?? "";

      /* ---- SSE streaming path ---- */
      if (res.ok && contentType.includes("text/event-stream") && res.body) {
        const reader = res.body.getReader();
        const decoder = new TextDecoder();
        let buffer = "";
        let finished = false;

        const handleEvent = (raw: string) => {
          const line = raw.trim();
          if (!line.startsWith("data:")) return;
          const data = line.slice(5).trim();
          if (!data || data === "[DONE]") return;
          try {
            const evt = JSON.parse(data) as {
              type: string;
              text?: string;
              refs?: string[];
              suggestReport?: boolean;
              message?: string;
            };
            if (evt.type === "delta" && typeof evt.text === "string") {
              // append incrementally (read current content from state)
              const current = get().chatMessages.find((m) => m.id === replyId);
              patchReply({ state: "streaming", content: (current?.content ?? "") + evt.text });
            } else if (evt.type === "done") {
              finished = true;
              patchReply({
                state: "done",
                refs: evt.refs,
                actions: evt.suggestReport ? { report: true } : undefined,
              });
            } else if (evt.type === "error") {
              finished = true;
              patchReply({
                state: "error",
                content: evt.message ?? "SASI could not answer right now.",
              });
            }
          } catch {
            /* partial JSON — ignore */
          }
        };

        while (true) {
          const { done, value } = await reader.read();
          if (done) break;
          buffer += decoder.decode(value, { stream: true });
          let sep: number;
          while ((sep = buffer.indexOf("\n")) !== -1) {
            const line = buffer.slice(0, sep);
            buffer = buffer.slice(sep + 1);
            if (line.trim()) handleEvent(line);
          }
        }
        if (buffer.trim()) handleEvent(buffer);

        if (!finished) {
          // stream ended without an explicit done/error — treat as done if we have text
          const current = get().chatMessages.find((m) => m.id === replyId);
          patchReply({
            state: (current?.content?.length ?? 0) > 0 ? "done" : "error",
            content:
              (current?.content?.length ?? 0) > 0
                ? current?.content
                : "The reply stream ended unexpectedly. Please try again.",
          });
        }
        set({ chatBusy: false });
        mirrorChat(get().chatMessages);
        return;
      }

      /* ---- JSON fallback path (older client/server mismatch) ---- */
      const data = (await res.json()) as {
        reply?: string;
        refs?: string[];
        suggestReport?: boolean;
        error?: string;
      };
      if (!res.ok || !data.reply) throw new Error(data.error ?? "SASI could not answer right now.");
      patchReply({
        content: data.reply,
        refs: data.refs,
        actions: data.suggestReport ? { report: true } : undefined,
        state: "done",
      });
      set({ chatBusy: false });
      mirrorChat(get().chatMessages);
    } catch (err) {
      /* user pressed stop — keep what already streamed in, honestly labelled */
      if (err instanceof DOMException && err.name === "AbortError") {
        const current = get().chatMessages.find((m) => m.id === replyId);
        const partial = current?.content ?? "";
        patchReply({
          state: "done",
          content:
            partial.trim().length > 0
              ? `${partial}\n\n*(Stopped — this answer may be incomplete.)*`
              : "*(Stopped before SASI started answering.)*",
        });
        set({ chatBusy: false });
        mirrorChat(get().chatMessages);
        return;
      }
      patchReply({
        content:
          err instanceof Error && err.message
            ? err.message
            : "SASI could not reach the assistant service. Please try again.",
        state: "error",
      });
      set({ chatBusy: false });
      mirrorChat(get().chatMessages);
    }
  },

  draftReportFromChat: (messageId) => {
    const msgs = get().chatMessages;
    const idx = msgs.findIndex((m) => m.id === messageId);
    const msg = msgs[idx];
    const lastUser = [...msgs.slice(0, idx < 0 ? msgs.length : idx)]
      .reverse()
      .find((m) => m.role === "user");
    const problem = (lastUser?.content ?? "").slice(0, 160) || "";
    set((s) => ({
      reportDraft: {
        service: s.reportDraft?.service ?? "water",
        problem,
        location: s.savedLocation.suburb
          ? `${s.savedLocation.suburb}, ${s.savedLocation.city}`
          : s.savedLocation.city,
        when: s.reportDraft?.when ?? "today",
        impact: s.reportDraft?.impact ?? "",
        evidenceNote: s.reportDraft?.evidenceNote ?? "",
      },
      view: "report",
      param: null,
      commandOpen: false,
    }));
    if (msg) {
      toast("Report wizard pre-filled", {
        description: "Your conversation gave SASI a head start — review and continue.",
      });
    }
  },
}));

/* The bridge itself: push a history entry on every real view change,
   and let popstate (Back/Forward/gestures) drive the store. Attached
   once, on the client only. */
if (typeof window !== "undefined") {
  useSasiStore.subscribe((s, prev) => {
    if (applyingPop) return;
    if (s.view === prev.view && s.param === prev.param) return;
    try {
      window.history.pushState({ sasi: true }, "", sasiUrlFor(s.view, s.param));
    } catch {
      /* history blocked — in-app navigation still works */
    }
  });
  window.addEventListener("popstate", applySasiUrl);
}

/* Dev/QA hook — lets browser automation drive the store directly
   (agent-browser eval). Stripped from production builds. */
if (process.env.NODE_ENV !== "production" && typeof window !== "undefined") {
  (window as unknown as { __sasiStore?: typeof useSasiStore }).__sasiStore =
    useSasiStore;
}
